// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wppvvwvyxcfgqgnhoqvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwcHZ2d3Z5eGNmZ3FnbmhvcXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODkzNzQsImV4cCI6MjA1OTY2NTM3NH0.jgT20sHZ7hadXYbLBTVzYTHwNwH7IAsCxK8Ku9wN1-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);